#!/usr/bin/env python3

import pathlib as pl, functools as ft
import os, sys, codecs, json, signal, warnings

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Keybinder', '3.0')
from gi.repository import Gtk, Gdk, GLib, GdkPixbuf, Gio

try: from gi.repository import Keybinder # libkeybinder3
except ImportError: Keybinder = None

try: import setproctitle # pip3 install --user proctitle
except ImportError: setproctitle = None

# Be sure to compile it with gcc first
import magnus_pixbuf_proc as mpp


p_err = ft.partial(print, file=sys.stderr, flush=True)

class adict(dict):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.__dict__ = self


class Magnus:

	def __init__(self, zoom, refresh_interval):
		self.zoomlevel = zoom
		self.app = Gtk.Application.new('org.jncDdHBql.K9LwUiqXJ.magnus', 0)
		self.decorations_width = self.decorations_height = 0
		self.last_x = self.last_y = -1
		self.refresh_interval = refresh_interval
		self.app.connect('activate', self.app_init)

	def app_init(self, app):
		GLib.set_application_name('Magnus')

		# the window
		self.w = Gtk.ApplicationWindow.new(self.app)
		self.w.set_size_request(300, 300)
		self.w.set_title('Magnus')
		self.w.connect('destroy', lambda a: self.app.quit())
		self.w.connect('configure-event', self.window_configure)
		self.w.connect('window-state-event', self.window_configure)
		self.w.connect('size-allocate', self.read_window_decorations_size)
		devman = self.w.get_screen().get_display().get_device_manager()
		self.pointer = devman.get_client_pointer()

		# the headerbar
		head = Gtk.HeaderBar()
		head.set_show_close_button(True)
		head.props.title = 'Magnus'
		self.w.set_titlebar(head)

		# the zoom chooser
		zoom = Gtk.ComboBoxText.new()
		self.zoom = zoom
		for n, x in enumerate(range(2, 6)):
			zoom.append(str(x), f'{x}×')
			if not n or x == self.zoomlevel: zoom.set_active(n)
		zoom.connect('changed', self.set_zoom)
		head.pack_end(zoom)

		# whole window is cairo drawing surface
		self.img = None
		self.da = Gtk.DrawingArea()
		self.da.set_hexpand(True)
		self.da.set_vexpand(True)
		self.da.connect('draw', self.draw)
		self.w.add(self.da)

		# bind the zoom keyboard shortcuts
		if Keybinder:
			Keybinder.init()
			if Keybinder.supported():
				Keybinder.bind('<Alt><Super>plus', self.zoom_in, zoom)
				Keybinder.bind('<Alt><Super>equal', self.zoom_in, zoom)
				Keybinder.bind('<Alt><Super>minus', self.zoom_out, zoom)

		# updates
		self.w_sz = adict(width=0, height=0)
		self.w_pos = adict(x=0, y=0)
		GLib.timeout_add(250, self.read_window_size)
		GLib.timeout_add(self.refresh_interval, self.update)

		# resize and present window
		self.w.show_all()


	def zoom_out(self, keypress, zoom):
		current_index = zoom.get_active()
		if current_index == 0: return
		zoom.set_active(current_index - 1)
		self.set_zoom(zoom)

	def zoom_in(self, keypress, zoom):
		current_index = zoom.get_active()
		size = zoom.get_model().iter_n_children(None)
		if current_index == size - 1: return
		zoom.set_active(current_index + 1)
		self.set_zoom(zoom)

	def read_window_decorations_size(self, win, alloc):
		sz = self.w.get_size()
		self.decorations_width = alloc.width - sz.width
		self.decorations_height = alloc.height - sz.height

	def set_zoom(self, zoom):
		self.zoomlevel = int(zoom.get_active_text()[0])
		self.update(force_refresh=True)
		self.serialise()

	def read_window_size(self, *args):
		self.w_sz = self.w.get_size()

	def window_configure(self, window, ev):
		self.read_window_size()
		if ev.type != Gdk.EventType.CONFIGURE: return
		self.w_pos = ev


	def update(self, force_refresh=False):
		display = Gdk.Display.get_default()
		screen, x, y, modifier = display.get_pointer()
		if x == self.last_x and y == self.last_y:
			# bail if nothing would be different
			if not force_refresh: return True
		self.last_x, self.last_y = x, y
		if (x > self.w_pos.x and
				x <= (self.w_pos.x + self.w_sz.width + self.decorations_width) and
				y > self.w_pos.y and
				y <= (self.w_pos.y + self.w_sz.height + self.decorations_height)):
			# pointer is over our window, so make it an empty pixbuf
			self.img = None
		else:
			root = Gdk.get_default_root_window()
			scaled_width = self.w_sz.width // self.zoomlevel
			scaled_height = self.w_sz.height // self.zoomlevel
			scaled_xoff = scaled_width // 2
			scaled_yoff = scaled_height // 2
			screenshot = Gdk.pixbuf_get_from_window(
				root, x - scaled_xoff,
				y - scaled_yoff, scaled_width, scaled_height)
			if screenshot:
				screenshot = self.tweak_colors(screenshot)
				screenshot = screenshot.scale_simple(
					self.w_sz.width, self.w_sz.height, GdkPixbuf.InterpType.NEAREST )
				self.img = Gdk.cairo_surface_create_from_pixbuf(screenshot, 0, None)
		self.da.queue_draw()
		return True

	def tweak_colors(self, screenshot):
		cs = screenshot.get_property('colorspace')
		if cs != GdkPixbuf.Colorspace.RGB:
			warnings.warn(f'Disabling color tweaks - unsupported colorspace: {cs}')
		else:
			w, h = screenshot.get_width(), screenshot.get_height()
			rs, buff = screenshot.get_rowstride(), screenshot.get_pixels()
			mpp.apply_curves(w, h, buff)
			screenshot = GdkPixbuf.Pixbuf.new_from_data(buff, cs, False, 8, w, h, rs)
		return screenshot

	def draw(self, da, ctx):
		w = da.get_allocation()
		w, h = w.width, w.height
		Gtk.render_background(da.get_style_context(), ctx, 0, 0, w, h)
		if not self.img: return
		ctx.set_source_surface(self.img, 0, 0)
		ctx.paint()


def main(args=None):
	import argparse
	parser = argparse.ArgumentParser(
		description='Simple screen magnifier tool with color tweaks.')
	parser.add_argument('-z', '--initial-zoom',
		type=int, metavar='level', default=2,
		help='Initial zoom level/factor. Default: %(default)sx')
	parser.add_argument('-r', '--refresh-interval',
		type=int, metavar='ms', default=250,
		help='Refresh interval in milliseconds (lower is faster). Default: %(default)s')
	opts = parser.parse_args(sys.argv[1:] if args is None else args)
	Magnus(opts.initial_zoom, opts.refresh_interval).app.run()

if __name__ == '__main__':
	warnings.filterwarnings('ignore', category=DeprecationWarning)
	signal.signal(signal.SIGINT, signal.SIG_DFL) # allow gtk to handle this (die quietly)
	if setproctitle: setproctitle.setproctitle('magnus')
	sys.exit(main())
